/**
 * Detection Rule Generator Utility
 * Synthesizes:
 *  1. Sigma Rules (Generic SIEM detection format)
 *  2. YARA Rules (Endpoint & memory artifact scanning)
 *  3. Splunk SPL Query (index=* sourcetype=* ...)
 *  4. Microsoft Sentinel KQL (CommonSecurityLog / DeviceNetworkEvents)
 *  5. CrowdStrike Falcon & Elastic EQL Queries
 *  6. Snort / Suricata IDS rule
 */

import { IndicatorType, IOCItem, MitreAttackRecord } from '../types/index.js';

export interface GeneratedDetectionPack {
  sigmaYaml: string;
  yaraRule: string;
  splunkQuery: string;
  sentinelKql: string;
  elasticEql: string;
  suricataRule: string;
}

function sanitizeIdentifier(name: string): string {
  return name.replace(/[^a-zA-Z0-9_]/g, '_').toLowerCase();
}

export function generateDetectionPack(params: {
  indicator: string;
  indicatorType: IndicatorType;
  verdict?: string;
  malwareFamily?: string;
  mitreTechniques?: MitreAttackRecord[];
  iocs?: IOCItem[];
  analystName?: string;
}): GeneratedDetectionPack {
  const {
    indicator,
    indicatorType,
    verdict = 'Malicious',
    malwareFamily = 'Suspicious_Threat',
    mitreTechniques = [],
    iocs = [],
    analystName = 'SOC Analyst'
  } = params;

  const dateStr = new Date().toISOString().split('T')[0];
  const ruleNameClean = sanitizeIdentifier(malwareFamily || indicator);
  const primaryMitre = mitreTechniques[0]?.technique_id || (indicatorType === 'hash' ? 'T1204.002' : 'T1071.001');

  // Collect related IOCs of relevant types
  const relatedIps = iocs.filter((i) => i.type === 'ip').map((i) => i.value);
  const relatedDomains = iocs.filter((i) => i.type === 'domain').map((i) => i.value);
  const relatedHashes = iocs.filter((i) => ['sha256', 'md5', 'sha1'].includes(i.type)).map((i) => i.value);

  // 1. Sigma Rule (YAML)
  let sigmaDetectionSection = '';
  if (indicatorType === 'hash') {
    const hashesList = [indicator, ...relatedHashes].slice(0, 5);
    sigmaDetectionSection = `  selection:
    Hashes|contains:
${hashesList.map((h) => `      - '${h}'`).join('\n')}
  condition: selection`;
  } else if (indicatorType === 'ip') {
    const ipsList = [indicator, ...relatedIps].slice(0, 5);
    sigmaDetectionSection = `  selection:
    DestinationIp:
${ipsList.map((ip) => `      - '${ip}'`).join('\n')}
  condition: selection`;
  } else if (indicatorType === 'domain') {
    const domainsList = [indicator, ...relatedDomains].slice(0, 5);
    sigmaDetectionSection = `  selection:
    query:
${domainsList.map((d) => `      - '*${d}*'`).join('\n')}
  condition: selection`;
  } else {
    // URL
    sigmaDetectionSection = `  selection:
    c-uri|contains:
      - '${indicator.replace(/https?:\/\//, '')}'
  condition: selection`;
  }

  const sigmaYaml = `title: Detect ${verdict} ${indicatorType.toUpperCase()} - ${malwareFamily || indicator}
id: ${Math.random().toString(36).substring(2, 10)}-${Math.random().toString(36).substring(2, 6)}-storm
status: experimental
description: Auto-generated by OPTIV S.T.O.R.M ThreatLense AI for verified indicator ${indicator}
references:
  - https://attack.mitre.org/techniques/${primaryMitre.replace(/\..*/, '')}/
author: ${analystName} (OPTIV ThreatLense AI)
date: ${dateStr}
modified: ${dateStr}
tags:
  - attack.${primaryMitre.toLowerCase().replace('.', '_')}
  - threat.${sanitizeIdentifier(malwareFamily || 'threat')}
logsource:
  category: ${indicatorType === 'hash' ? 'process_creation' : indicatorType === 'domain' ? 'dns_query' : 'network_connection'}
  product: windows
detection:
${sigmaDetectionSection}
falsepositives:
  - Legitimate administrative tooling or third-party cloud infrastructure
level: ${verdict.toLowerCase() === 'malicious' ? 'critical' : 'high'}`;

  // 2. YARA Rule
  let yaraStrings = '';
  if (indicatorType === 'hash') {
    yaraStrings = `    $hash_sha256 = "${indicator.length === 64 ? indicator : ''}" ascii wide nocase
    $magic_mz = "MZ"
    $threat_tag = "${malwareFamily}" ascii wide nocase`;
  } else if (indicatorType === 'domain') {
    yaraStrings = `    $c2_domain = "${indicator}" ascii wide nocase
    $http_user_agent = "Mozilla/5.0" ascii wide nocase
    $c2_endpoint = "/login" ascii wide nocase`;
  } else if (indicatorType === 'ip') {
    yaraStrings = `    $c2_ip = "${indicator}" ascii wide nocase
    $c2_beacon = "POST " ascii wide nocase`;
  } else {
    yaraStrings = `    $malicious_url = "${indicator}" ascii wide nocase`;
  }

  const yaraRule = `import "pe"

rule Storm_Detect_${ruleNameClean}_${dateStr.replace(/-/g, '')} {
    meta:
        description = "Detects artifacts associated with ${indicator} (${malwareFamily})"
        author = "${analystName} via OPTIV S.T.O.R.M"
        reference = "MITRE ${primaryMitre}"
        date = "${dateStr}"
        tlp = "AMBER"
        hash = "${indicatorType === 'hash' ? indicator : 'N/A'}"
        score = 85

    strings:
${yaraStrings}

    condition:
        ${indicatorType === 'hash' ? 'uint16(0) == 0x5A4D and any of ($hash_sha256, $threat_tag)' : 'any of them'}
}`;

  // 3. Splunk SPL Query
  let splunkQuery = '';
  if (indicatorType === 'ip') {
    splunkQuery = `index=* (src_ip="${indicator}" OR dest_ip="${indicator}" OR c_ip="${indicator}")
| stats count earliest(_time) as first_seen latest(_time) as last_seen by host, user, src_ip, dest_ip, dest_port
| eval threat_indicator="${indicator}", verdict="${verdict}"
| convert ctime(first_seen) ctime(last_seen)`;
  } else if (indicatorType === 'domain') {
    splunkQuery = `index=* (query="*${indicator}*" OR domain="*${indicator}*" OR url="*${indicator}*")
| stats count earliest(_time) as first_seen latest(_time) as last_seen by host, user, query, src_ip
| eval threat_indicator="${indicator}", verdict="${verdict}"
| convert ctime(first_seen) ctime(last_seen)`;
  } else if (indicatorType === 'hash') {
    splunkQuery = `index=* (file_hash="${indicator}" OR hash="${indicator}" OR process_hash="*${indicator}*")
| stats count earliest(_time) as first_seen latest(_time) as last_seen by host, user, file_name, process_path
| eval threat_indicator="${indicator}", verdict="${verdict}"
| convert ctime(first_seen) ctime(last_seen)`;
  } else {
    splunkQuery = `index=* url="*${indicator.replace(/https?:\/\//, '')}*"
| stats count earliest(_time) as first_seen latest(_time) as last_seen by host, user, url, status
| eval threat_indicator="${indicator}", verdict="${verdict}"
| convert ctime(first_seen) ctime(last_seen)`;
  }

  // 4. Microsoft Sentinel KQL
  let sentinelKql = '';
  if (indicatorType === 'ip') {
    sentinelKql = `let targetIp = "${indicator}";
search in (CommonSecurityLog, DeviceNetworkEvents, DnsEvents)
    TimeGenerated >= ago(7d)
    and (DestinationIP == targetIp or SourceIP == targetIp or RemoteIP == targetIp)
| project TimeGenerated, DeviceName, SourceIP, DestinationIP, RemoteIP, ActionType, ThreatSeverity = "${verdict}"
| sort by TimeGenerated desc`;
  } else if (indicatorType === 'domain') {
    sentinelKql = `let targetDomain = "${indicator}";
search in (DnsEvents, DeviceNetworkEvents, UrlClickEvents)
    TimeGenerated >= ago(7d)
    and (Name has targetDomain or RemoteUrl has targetDomain or Url has targetDomain)
| project TimeGenerated, DeviceName, ClientIP, RemoteUrl, ActionType, ThreatSeverity = "${verdict}"
| sort by TimeGenerated desc`;
  } else if (indicatorType === 'hash') {
    sentinelKql = `let targetHash = "${indicator}";
DeviceFileEvents
| where TimeGenerated >= ago(14d)
| where SHA256 == targetHash or MD5 == targetHash
| project TimeGenerated, DeviceName, ActionType, FileName, FolderPath, InitiatingProcessCommandLine, AccountName
| sort by TimeGenerated desc`;
  } else {
    sentinelKql = `let targetUrl = "${indicator.replace(/https?:\/\//, '')}";
UrlClickEvents
| where TimeGenerated >= ago(7d)
| where Url has targetUrl
| project TimeGenerated, AccountUpn, Url, ActionType, ThreatType = "Phishing/Malicious"
| sort by TimeGenerated desc`;
  }

  // 5. Elastic EQL
  let elasticEql = '';
  if (indicatorType === 'hash') {
    elasticEql = `process where event.type == "start" and (process.hash.sha256 == "${indicator}" or process.hash.md5 == "${indicator}")`;
  } else if (indicatorType === 'ip') {
    elasticEql = `network where event.type == "connection" and (destination.ip == "${indicator}" or source.ip == "${indicator}")`;
  } else if (indicatorType === 'domain') {
    elasticEql = `dns where dns.question.name == "${indicator}"`;
  } else {
    elasticEql = `network where event.category == "web" and url.full contains "${indicator.replace(/https?:\/\//, '')}"`;
  }

  // 6. Suricata / Snort IDS Rule
  let suricataRule = '';
  const sid = 1000000 + Math.floor(Math.random() * 900000);
  if (indicatorType === 'domain') {
    suricataRule = `alert dns $HOME_NET any -> any any (msg:"OPTIV-STORM ThreatLense AI DNS query to malicious domain ${indicator}"; dns.query; content:"${indicator}"; nocase; classtype:trojan-activity; sid:${sid}; rev:1;)`;
  } else if (indicatorType === 'ip') {
    suricataRule = `alert ip $HOME_NET any -> ${indicator} any (msg:"OPTIV-STORM ThreatLense AI Outbound traffic to known C2 ${indicator}"; flow:to_server,established; classtype:trojan-activity; sid:${sid}; rev:1;)`;
  } else if (indicatorType === 'url') {
    const urlPath = indicator.replace(/https?:\/\/[^\/]+/, '') || '/';
    suricataRule = `alert http $HOME_NET any -> any any (msg:"OPTIV-STORM ThreatLense AI Malicious HTTP request to ${indicator}"; http.uri; content:"${urlPath}"; nocase; classtype:bad-unknown; sid:${sid}; rev:1;)`;
  } else {
    suricataRule = `# Network signature not applicable directly for hash indicator. Use Sigma/YARA for file artifact containment.
alert tcp $HOME_NET any -> any any (msg:"OPTIV-STORM IOC Payload hash ${indicator.substring(0, 16)} alert"; sid:${sid}; rev:1;)`;
  }

  return {
    sigmaYaml,
    yaraRule,
    splunkQuery,
    sentinelKql,
    elasticEql,
    suricataRule
  };
}
